server.port=8082
spring.application.name=topic-service
spring.jackson.time-zone=Asia/Hong_Kong
spring.jackson.serialization.write-dates-as-timestamps=false
spring.datasource.url=jdbc:mysql://localhost:3306/shareudb?serverTimezone=Asia/Hong_Kong
spring.datasource.username=root
spring.datasource.password=ShareUComp4442
spring.flyway.enabled=false
